const SIGNAL_PAIRS = [
  "BTCUSDT",
  "ETHUSDT",
  "BNBUSDT",
  "SOLUSDT",
  "XRPUSDT",
  "ADAUSDT",
  "DOGEUSDT",
  "TONUSDT",
  "AVAXUSDT",
  "SHIBUSDT",
  "DOTUSDT",
  "TRXUSDT",
  "LINKUSDT",
  "MATICUSDT",
  "LTCUSDT",
];

const SUPPORTED_SIGNAL_TIMEFRAMES = ["15m"];
const SIGNAL_TIMEFRAME = SUPPORTED_SIGNAL_TIMEFRAMES.includes(String(process.env.SIGNAL_TIMEFRAME || "").trim())
  ? String(process.env.SIGNAL_TIMEFRAME || "").trim()
  : "15m";
const SIGNAL_HISTORY_LIMIT = 260;
const LEVEL_LOOKBACK = 80;
const SIGNAL_COOLDOWN_MS = 12 * 60 * 1000;
const SIGNAL_EXPIRY_MS = 24 * 60 * 60 * 1000;
const MAX_SIGNAL_HISTORY = 500;
const MIN_CONFIDENCE = 60;
const DEFAULT_STATUS = "active";
const ACTIVE_SIGNAL_STATUS = "active";
const DELETED_SIGNAL_STATUS = "deleted";
const EXPIRED_SIGNAL_STATUS = "expired";

module.exports = {
  ACTIVE_SIGNAL_STATUS,
  DEFAULT_STATUS,
  DELETED_SIGNAL_STATUS,
  EXPIRED_SIGNAL_STATUS,
  LEVEL_LOOKBACK,
  MAX_SIGNAL_HISTORY,
  MIN_CONFIDENCE,
  SIGNAL_COOLDOWN_MS,
  SIGNAL_EXPIRY_MS,
  SIGNAL_HISTORY_LIMIT,
  SIGNAL_PAIRS,
  SIGNAL_TIMEFRAME,
  SUPPORTED_SIGNAL_TIMEFRAMES,
};
