const SIGNAL_PAIRS = [
  "BTCUSDT",
  "ETHUSDT",
  "BNBUSDT",
  "SOLUSDT",
  "XRPUSDT",
  "ADAUSDT",
  "DOGEUSDT",
  "TONUSDT",
  "AVAXUSDT",
  "SHIBUSDT",
  "DOTUSDT",
  "TRXUSDT",
  "LINKUSDT",
  "MATICUSDT",
  "LTCUSDT",
];

const SIGNAL_TIMEFRAME = "5m";
const SIGNAL_HISTORY_LIMIT = 140;
const LEVEL_LOOKBACK = 80;
const SIGNAL_COOLDOWN_MS = 12 * 60 * 1000;
const MAX_SIGNAL_HISTORY = 120;
const MIN_CONFIDENCE = 60;
const DEFAULT_STATUS = "BUY_READY";

module.exports = {
  DEFAULT_STATUS,
  LEVEL_LOOKBACK,
  MAX_SIGNAL_HISTORY,
  MIN_CONFIDENCE,
  SIGNAL_COOLDOWN_MS,
  SIGNAL_HISTORY_LIMIT,
  SIGNAL_PAIRS,
  SIGNAL_TIMEFRAME,
};
